### PR TITLE
Generate hugo documentation markdown

### PR DESCRIPTION
**Pull request by johanstokking**
#### Summary

Generate hugo documentation in Markdown

#### Changes

Add `gen hugodoc` commands to `pbadmin`, `pbctl`, `pbsub` and `pbpub`

#### Notes for Reviewers

Usage:

```bash
$ pbadmin gen hugodoc
```

Results in a bunch of Markdown files (specify destination directory with `--out`).

### CODE REVIEW

**Comment by benolayinka** [comment]
Do I need credentials to run this?

```
ben@AirvonBenjamin pb % go run cmd/pbctl/main.go gen hugodoc           
Error: no credentials
```

**Comment by benolayinka** [comment]
```
ben@AirvonBenjamin pb % go run cmd/pbsub/main.go gen hugodoc
Error: missing server address
```

**Comment by benolayinka** [comment]
@johanstokking ?

**Comment by johanstokking** [comment]
Fixed that, fetch and try again

**Comment by johanstokking** [comment]
@benolayinka is it working now? Are you going to use this?

**Comment by benolayinka** [comment]
> @benolayinka is it working now? Are you going to use this?

yep but can we also export a command tree somehow to make the nav more useful?

Bildschirmfoto 2021-06-28 um 11 03 46

**Comment by johanstokking** [comment]
Yes sure, please tell me what exactly to output. Do we need partials, a tree file (and what does the tree look like: example), output markdowns in a folder structure.

TTS CLI isn't a good reference. I don't want to maintain files like https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/content/reference/cli/gateways.md here.

Please a simple reference output and I'll see what I can do to generate that.

**Comment by benolayinka** [comment]
> Yes sure, please tell me what exactly to output. Do we need partials, a tree file (and what does the tree look like: example), output markdowns in a folder structure.
> 
> TTS CLI isn't a good reference. I don't want to maintain files like https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/content/reference/cli/gateways.md here.
> 
> Please a simple reference output and I'll see what I can do to generate that.

json example, something like this borrowed from here -> https://stackoverflow.com/questions/37150668/json-schema-for-tree-structure

```
{
id: pbadmin,
children: [
  {
    id: cluster,
    children: [
      {
        id: apikey
      },
    ]
  },
  {
    id: gen,
    children: [
    ],
  },
],
}
```

**Comment by johanstokking** [comment]
OK, please check:

```bash
$ go install go.packetbroker.org/pb/cmd/pbadmin@30872c6
$ pbadmin gen tree --out tree.json
```

And see `tree.json`:

```json
{
  "pbadmin": {
    "short": "pbadmin can be used to manage networks, tenants and API keys.",
    "path": "pbadmin",
    "subCommands": {
      "cluster": {
        "short": "Manage Packet Broker clusters",
        "path": "pbadmin cluster",
        "subCommands": {
          "apikey": {
            "short": "Manage Packet Broker API keys for clusters",
            "path": "pbadmin cluster apikey",
            "subCommands": {
              "create": {
                "short": "Create an API key",
                "path": "pbadmin cluster apikey create"
              },
              "delete": {
                "short": "Delete an API key",
                "path": "pbadmin cluster apikey delete"
              },
              "list": {
                "short": "List API keys",
                "path": "pbadmin cluster apikey list"
              },
              "update-state": {
                "short": "Update the API key state",
                "path": "pbadmin cluster apikey update-state"
              }
            }
          }
        }
      },
      "gen": {
        "short": "Generation commands",
        "path": "pbadmin gen",
        "subCommands": {
          "hugodoc": {
            "short": "Generate documentation for Hugo",
            "path": "pbadmin gen hugodoc"
          },
          "tree": {
            "short": "Generate command tree",
            "path": "pbadmin gen tree"
          }
        }
      },
      "help": {
        "short": "Help about any command",
        "path": "pbadmin help"
      },
      "network": {
        "short": "Manage Packet Broker networks",
        "path": "pbadmin network",
        "subCommands": {
          "apikey": {
            "short": "Manage Packet Broker API keys for networks and tenants",
            "path": "pbadmin network apikey",
            "subCommands": {
              "create": {
                "short": "Create an API key",
                "path": "pbadmin network apikey create"
              },
              "delete": {
                "short": "Delete an API key",
                "path": "pbadmin network apikey delete"
              },
              "list": {
                "short": "List API keys",
                "path": "pbadmin network apikey list"
              },
              "update-state": {
                "short": "Update the API key state",
                "path": "pbadmin network apikey update-state"
              }
            }
          },
          "create": {
            "short": "Create a network",
            "path": "pbadmin network create"
          },
          "delete": {
            "short": "Delete a network",
            "path": "pbadmin network delete"
          },
          "get": {
            "short": "Get a network",
            "path": "pbadmin network get"
          },
          "init": {
            "short": "Initialize network configuration",
            "path": "pbadmin network init"
          },
          "list": {
            "short": "List networks",
            "path": "pbadmin network list"
          },
          "tenant": {
            "short": "Manage Packet Broker tenants",
            "path": "pbadmin network tenant",
            "subCommands": {
              "create": {
                "short": "Create a tenant",
                "path": "pbadmin network tenant create"
              },
              "delete": {
                "short": "Delete a tenant",
                "path": "pbadmin network tenant delete"
              },
              "get": {
                "short": "Get a tenant",
                "path": "pbadmin network tenant get"
              },
              "list": {
                "short": "List tenants",
                "path": "pbadmin network tenant list"
              },
              "update": {
                "short": "Update a tenant",
                "path": "pbadmin network tenant update",
                "subCommands": {
                  "target": {
                    "short": "Update a tenant target",
                    "path": "pbadmin network tenant update target"
                  }
                }
              }
            }
          },
          "update": {
            "short": "Update a network",
            "path": "pbadmin network update",
            "subCommands": {
              "target": {
                "short": "Update a network target",
                "path": "pbadmin network update target"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by benolayinka** [comment]
> OK, please check:
> 
> ```shell
> $ go install go.packetbroker.org/pb/cmd/pbadmin@30872c6
> $ pbadmin gen tree --out tree.json
> ```
> 
> And see `tree.json`:
> 
> ```json
> {
>   "pbadmin": {
>     "short": "pbadmin can be used to manage networks, tenants and API keys.",
>     "path": "pbadmin",
>     "subCommands": {
>       "cluster": {
>         "short": "Manage Packet Broker clusters",
>         "path": "pbadmin cluster",
>         "subCommands": {
>           "apikey": {
>             "short": "Manage Packet Broker API keys for clusters",
>             "path": "pbadmin cluster apikey",
>             "subCommands": {
>               "create": {
>                 "short": "Create an API key",
>                 "path": "pbadmin cluster apikey create"
>               },
>               "delete": {
>                 "short": "Delete an API key",
>                 "path": "pbadmin cluster apikey delete"
>               },
>               "list": {
>                 "short": "List API keys",
>                 "path": "pbadmin cluster apikey list"
>               },
>               "update-state": {
>                 "short": "Update the API key state",
>                 "path": "pbadmin cluster apikey update-state"
>               }
>             }
>           }
>         }
>       },
>       "gen": {
>         "short": "Generation commands",
>         "path": "pbadmin gen",
>         "subCommands": {
>           "hugodoc": {
>             "short": "Generate documentation for Hugo",
>             "path": "pbadmin gen hugodoc"
>           },
>           "tree": {
>             "short": "Generate command tree",
>             "path": "pbadmin gen tree"
>           }
>         }
>       },
>       "help": {
>         "short": "Help about any command",
>         "path": "pbadmin help"
>       },
>       "network": {
>         "short": "Manage Packet Broker networks",
>         "path": "pbadmin network",
>         "subCommands": {
>           "apikey": {
>             "short": "Manage Packet Broker API keys for networks and tenants",
>             "path": "pbadmin network apikey",
>             "subCommands": {
>               "create": {
>                 "short": "Create an API key",
>                 "path": "pbadmin network apikey create"
>               },
>               "delete": {
>                 "short": "Delete an API key",
>                 "path": "pbadmin network apikey delete"
>               },
>               "list": {
>                 "short": "List API keys",
>                 "path": "pbadmin network apikey list"
>               },
>               "update-state": {
>                 "short": "Update the API key state",
>                 "path": "pbadmin network apikey update-state"
>               }
>             }
>           },
>           "create": {
>             "short": "Create a network",
>             "path": "pbadmin network create"
>           },
>           "delete": {
>             "short": "Delete a network",
>             "path": "pbadmin network delete"
>           },
>           "get": {
>             "short": "Get a network",
>             "path": "pbadmin network get"
>           },
>           "init": {
>             "short": "Initialize network configuration",
>             "path": "pbadmin network init"
>           },
>           "list": {
>             "short": "List networks",
>             "path": "pbadmin network list"
>           },
>           "tenant": {
>             "short": "Manage Packet Broker tenants",
>             "path": "pbadmin network tenant",
>             "subCommands": {
>               "create": {
>                 "short": "Create a tenant",
>                 "path": "pbadmin network tenant create"
>               },
>               "delete": {
>                 "short": "Delete a tenant",
>                 "path": "pbadmin network tenant delete"
>               },
>               "get": {
>                 "short": "Get a tenant",
>                 "path": "pbadmin network tenant get"
>               },
>               "list": {
>                 "short": "List tenants",
>                 "path": "pbadmin network tenant list"
>               },
>               "update": {
>                 "short": "Update a tenant",
>                 "path": "pbadmin network tenant update",
>                 "subCommands": {
>                   "target": {
>                     "short": "Update a tenant target",
>                     "path": "pbadmin network tenant update target"
>                   }
>                 }
>               }
>             }
>           },
>           "update": {
>             "short": "Update a network",
>             "path": "pbadmin network update",
>             "subCommands": {
>               "target": {
>                 "short": "Update a network target",
>                 "path": "pbadmin network update target"
>               }
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```

this is perfect, but it looks like `gen hugodoc` is not creating docs for the help files, though they are referenced in the json

`REF_NOT_FOUND: Ref "/commands/pbadmin/pbadmin_help" from page "commands/pbadmin/pbadmin_cluster_apikey_list.md": page not found`

Bildschirmfoto 2021-06-28 um 17 34 40

**Comment by johanstokking** [comment]
OK, please check with `baafadf`

**Comment by johanstokking** [comment]
So:

```bash
$ go install go.packetbroker.org/pb/cmd/pbadmin@baafadf
$ go install go.packetbroker.org/pb/cmd/pbctl@baafadf
$ go install go.packetbroker.org/pb/cmd/pbsub@baafadf
$ go install go.packetbroker.org/pb/cmd/pbpub@baafadf
```

And then the respective `gen tree` commands

**Comment by benolayinka** [comment]
> So:
> 
> ```shell
> $ go install go.packetbroker.org/pb/cmd/pbadmin@baafadf
> $ go install go.packetbroker.org/pb/cmd/pbctl@baafadf
> $ go install go.packetbroker.org/pb/cmd/pbsub@baafadf
> $ go install go.packetbroker.org/pb/cmd/pbpub@baafadf
> ```
> 
> And then the respective `gen tree` commands

works now. i added a script to the docs to clone and generate everything

```
git clone https://github.com/packetbroker/pb.git

cd pb

mkdir ../doc/content/commands
mkdir ../doc/data/commands

for i in pbsub pbpub pbadmin pbctl
do
	mkdir ../doc/content/commands/$i
	go run cmd/$i/main.go gen hugodoc --out ../doc/content/commands/$i
	go run cmd/$i/main.go gen tree --out ../doc/data/commands/$i.json
done
```

**Comment by johanstokking** [comment]
Please use a Makefile for that and make sure things are reproduceable.

For example:

```Makefile
# Makefile
SHELL = bash
GO = go
GOBIN = $(PWD)/.bin
export GOBIN

.PHONY: deps.dev
deps.dev:
	@cat tools.go | grep _ | awk -F'"' '{print $$2}' | xargs -tI % $(GO) install %

.PHONY: gen.cli
gen.cli:
	@mkdir -p data/commands
	@$(GOBIN)/pbadmin gen hugodoc --out data/commands
	@$(GOBIN)/pbadmin gen tree --out data/tree.json
```

```go
// tools.go
// +build tools

package main

import (
	_ "go.packetbroker.org/pb/cmd/pbadmin"
)
```

```gomod
// go.mod
module go.packetbroker.org/docs

go 1.16

require (
	github.com/spf13/viper v1.8.1 // indirect
	go.packetbroker.org/api/iam v1.5.3 // indirect
	go.packetbroker.org/api/iam/v2 v2.6.2 // indirect
	go.packetbroker.org/pb v0.0.0-20210629072335-baafadf27bad
	golang.org/x/net v0.0.0-20210614182718-04defd469f4e // indirect
	golang.org/x/oauth2 v0.0.0-20210622215436-a8dc77f794b6 // indirect
	golang.org/x/sys v0.0.0-20210616094352-59db8d763f22 // indirect
	golang.org/x/term v0.0.0-20210615171337-6886f2dfbf5b // indirect
	google.golang.org/genproto v0.0.0-20210624195500-8bfb893ecb84 // indirect
)
```

We can then upgrade the version with `go get go.packetbroker.org/pb/...` and `go mod tidy` and we can always go back and forth between versions.

**Comment by johanstokking** [comment]
If there are no changes required here, please approve.

**Review by benolayinka — APPROVED** [review]

**Pull request merged**
